### ISSUE TITLE
Rich Presence Missing Time Remaining 

### ISSUE THREAD

**Issue by nikoptune** [jojo2357/Music-Discord-Rich-Presence#100]
**Version**
The version the bug was found on: 1.7.3

**Describe the bug**
Rich presence no longer shows the seek bar when viewing profiles, nor does it show time remaining. It only shows the song info.

**Expected behavior**
The seek bar previously appeared, along with current song progress & time remaining.

**Screenshots**
![image](https://github.com/user-attachments/assets/5fde98b2-8849-4c67-b123-573609a18231)

**Comment by jojo2357** [comment]
Are you still using the required Musicbee plugin?

**Comment by nikoptune** [comment]
Yep.

![image](https://github.com/user-attachments/assets/92526335-2622-4d17-9641-08e8556b0261)

**Comment by jojo2357** [comment]
Have you restarted MDRP + MB?

**Comment by nikoptune** [comment]
I have. Still doesn't appear, but the song info works fine.

**Comment by jojo2357** [comment]
Can you show me the MDRP console? 

Have you tried running the debug server?

**Comment by nikoptune** [comment]
Console seems fine to me?

![image](https://github.com/user-attachments/assets/c219b9d1-f0d1-4c8c-a156-f3003c4cf70b)

Not sure how to use the debug server, sorry. It's been a while since I did anything node related.

**Comment by jojo2357** [comment]
do you have the time remaining reported at the time of the ss?

**Comment by nikoptune** [comment]
Rich presence still does not show the time remaining. It does, strangely, show up on mobile. Only other difference from yesterday (when it still worked) to today is that my profile/account has the "Activity history" experiment active now.

**Comment by jojo2357** [comment]
Hm, I know that as of recently, buttons are not able to be seen on your own profile. Definitely see if others can see it reliably. It might be a discord issue!

**Comment by nikoptune** [comment]
This is a few examples I've gotten from others.

Time remaining visible but no seek bar.
![image](https://github.com/user-attachments/assets/2ff4ee8a-f918-47c1-8f82-758c616cc5c9)
![image](https://github.com/user-attachments/assets/96aaf300-c7bb-4c76-b976-a1d058f2072e)

Now that I think about it, it probably never had the seek bar...haha. Oops! Though I do remember the time remaining for sure, and it's gone on my end now that the Activity history is a thing (assuming its related), but not for others.

**Comment by jojo2357** [comment]
Yeah...i think you might have confused Spotify (they pay to win :() with MDRP.

I am closing this as a Discord issue *sigh*

**Comment by nikoptune** [comment]
Appreciate the swift responses, though! :)
