### ISSUE TITLE
Program bugs out if there's a space in the parent folder's name

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence#16]
The program runs fine, when the file naming contains no space in the parent folder's path/name, but with a space in the parent folder name it shows the error as shown in the attached screenshot.

![error screenshot](https://user-images.githubusercontent.com/39442192/110825137-bd372300-82b9-11eb-9741-5911d9dfe8b7.png)

**Comment by jojo2357** [comment]
I think I know how to fix this, thank you

**Comment by jojo2357** [comment]
oops i auto closed it but update your `RunHidden.vbs` file with the changed one (found in `GroovyRP/bin/Release`) and reopen if that didnt fix it

**Comment by RoguedBear** [comment]
yes 22ada488250b1ea9cb05de4811acd4bbe47732d8 fixes the problem!
thank you for your quick and speedy fix :zap: :)
