### ISSUE TITLE
Album title too long

### ISSUE THREAD

**Issue by Javonski** [jojo2357/Music-Discord-Rich-Presence#21]
Tried to play a song, here's what DRP has to say: (Length of string is out of range. Expected a value with a maximum length of 32)
![image](https://user-images.githubusercontent.com/66522068/111160973-963c6200-85d5-11eb-9da4-1861e665980b.png)

Thus resulting to this:
![image](https://user-images.githubusercontent.com/66522068/111161330-01863400-85d6-11eb-879d-5b34c9d5a9c0.png)

Here is what the album title looks like lmao: 
![image](https://user-images.githubusercontent.com/66522068/111161045-aa805f00-85d5-11eb-8620-eabc3565708d.png)

And it's written in the .dat file as "dinnerisnotovertheressomethinghappeningkeymancupid" (50 characters). Is there a workaround for this?

**Comment by jojo2357** [comment]
😂 ill look into it

**Comment by jojo2357** [comment]
Discord doesnt support image assets longer then 32 characters so you will have to change the key. Workaround `Dinner Is Not Over / There's Something Happening / Keyman / Cupid=dinnerisnotover`

**Comment by jojo2357** [comment]
Check recent commit and close if fixed

**Comment by Javonski** [comment]
Ah, I see, so I just needed to change the name of the art in the discord app, why didn't I realize that? lmao
So I'm still waiting for the album art to appear on rich presence, I have some questions for the meantime.

I can include special characters in the AlbumName like the slash, period, comma, or spaces and the program will just ignore them except for the equal sign. Is that correct?

Also, in the unfortunate case where two albums have the same name, what happens then?

**Comment by Javonski** [comment]
Sweet! It's working
![image](https://user-images.githubusercontent.com/66522068/111237698-93228f80-8630-11eb-89d1-e0fff98dd5ce.png)
I'm closing this issue now but I'm leaving the questions above open.
