### ISSUE TITLE
Suggestion: Contributing Album Art to the main repository instead of creating individual application

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence#23]
by contributing the album art to the main repository, you can end up with a huge collection of album arts to make it kinda like a mini spotify game activity.

Since there are a diverse range of songs, this could only work if discord has no limit to how many art assets can be added for rich presence. I tried searching if a limit exists, but I couldn't find anything related to that

**Comment by jojo2357** [comment]
There is a per-application limit of 150 (see image). The only thing im worried about is if images are wrong (since they are controlled by a third party) or the application name is inappropriate. I am open to making a new repo where people send in their album art and then me or @Smaltin make and maintain the library. Lmk what you think.
![image](https://user-images.githubusercontent.com/66704796/111260046-5da08680-85dd-11eb-909c-9eebbd8ce0ce.png)

**Comment by RoguedBear** [comment]
So basically, the collection of album arts could be possible by creating many many applications on discord and using their client ids in the main repo?

Then your concerns for inaccurate album art and inappropriate app names are valid. This could be a problem when this repo gets a large number of users but i guess for a small userbase it could be manageable.

I was also thinking of 2 ways to organise the album arts.
 1) could be just creating applications and filling them up with album art when someone requests it or needs it till it reaches 150 limit
 2) sort the album art by creating an application artist-wise. An application to contain album arts of an artist for all their albums.

Thanks to your instructions and format of the config file it is really easy to add album arts.

(PS: is there a limit on discord how many applications can be created?)

**Comment by jojo2357** [comment]
I suppose by artist would work and would make it easy. I dunno if theres an application limit but theres no discord account limit so I could make as many as I want in theory. If only there was a fast way to upload art I would be able to automate the process but instead I have to do it by hand which I suppose is doable. I can make a library repository that will accept images turned into asset files.

**Comment by RoguedBear** [comment]
For getting the album art from the mp3 and resizing it I've simplified those steps to a few clicks.

earlier I was looking for album art on wikipedia, downloading and and resizing it, but now I'm getting the album art from the mp3 itself, i have downloaded.

- [This](https://unix.stackexchange.com/a/41288) answer on stackexchange tells how you can extract album art from the mp3 from command line
- and for resizing i use the ImageResizer module in [PowerToys](https://github.com/microsoft/PowerToys) (ofc you can use anything else)

When I was adding album art to my application, getting the album art from the internet was the time consuming and painful part, but 1st point above makes it _less_ painful, But still cumbersome.
Uploading seems less painful for 3-4 album arts, but for tens of files i can imagine those being tiring and error prone

Maybe i could make a python script to automate both these steps broadly.
- one script to extract the album art from a huge collection of mp3s which have different album names
- and the other to batch upload those pictures with a python-selenium script in an already open discord application tab
- and _maybe_ also generate a `.dat` file of `song_name=discord_image_name`

**Comment by jojo2357** [comment]
I'll look into it, thanks

**Comment by jojo2357** [comment]
Okay so heres what i have done so far: 
- Created a way to rip all album arts from mp3's in a directory and all subdirectories
- Created a way to download all album arts for a spotify playlist (this is on a website that I made so definitely not the best)
- takes downloaded images and keys them and constructs key files and places them inside a dat formatted properly alongside the correct keyed images.

These were written in javascript (nodejs) so i would have to work to create a native executable. Im thinking that i will make another repo where people can pr with generated clientdata folders and I will create the applications and add them to a library.

**Comment by RoguedBear** [comment]
wow this was done so fast!
A library-repo for people to PR their album art and clientdata folder is a great idea. I would be looking forward to contribute album arts from my collection! 😃

**Comment by jojo2357** [comment]
[The library](https://github.com/jojo2357/Music-Discord-Rich-Presence-Library) is now open for people to try out (I am still streamlining how it will go but for now, there it is
