### ISSUE TITLE
Release zip file has repeated "taskkill" in KillHidden.vbs whereas the repo code does not

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence#24]
## Concerned File:
[KillHidden.vbs](https://github.com/jojo2357/Music-Discord-Rich-Presence/blob/master/GroovyRP/bin/Release/KillHidden.vbs)

## Description:
I was digging into why the GroovyRP was not closing when I closed Groove, and here's this weird thing I found:

The `KillHidden.vbs` _in the zip file_ from the [Release](https://github.com/jojo2357/Music-Discord-Rich-Presence/releases/tag/1.3.4) page contains the code as shared in the below screenshot:

![image](https://user-images.githubusercontent.com/39442192/111308457-b543fe00-8680-11eb-859b-b6a9cfa0c6db.png)

Whereas the code for the same file is correct one in the repository [here](https://github.com/jojo2357/Music-Discord-Rich-Presence/blob/0799aff3df3ef4c9f756e1969c6d206725ee8381/GroovyRP/bin/Release/KillHidden.vbs):

https://github.com/jojo2357/Music-Discord-Rich-Presence/blob/0799aff3df3ef4c9f756e1969c6d206725ee8381/GroovyRP/bin/Release/KillHidden.vbs#L2 :

**Comment by jojo2357** [comment]
Doh! I had just found and fixed it guess i forgot to make a release.

**Comment by jojo2357** [comment]
Confirm 1.4.0 fixes this then close or lmk

**Comment by RoguedBear** [comment]
yes, 1.4.0 fixes it!
