### ISSUE TITLE
Notifications require you to allow to run

### ISSUE THREAD

**Issue by Smaltin** [jojo2357/Music-Discord-Rich-Presence#25]
Since everything is unsigned, it's an extra step every time I want to receive a notification unless I allow it to run all the time.
![image](https://user-images.githubusercontent.com/6719266/111858864-69e85480-88f9-11eb-8bc7-9d10d9c4aab4.png)

**Comment by jojo2357** [comment]
Well i guess ill be using c# built in methods. I already had the bat lying around so I figured I would just use it. Expect 1.4.3 to be out soon then

**Comment by jojo2357** [comment]
Please verify 1.4.3 works to your satisfaction then close
