### ISSUE TITLE
Shortcut paths are designed for developer

### ISSUE THREAD

**Issue by ODAKAB** [jojo2357/Music-Discord-Rich-Presence#26]
I had to manually modify all of their paths, I will make a pull request for automating it when i have some time. With use of batch scripts.

**Comment by jojo2357** [comment]
Ah shoes. I used to change all of the shortcuts since i create new folders to create releases but its kinda a lot of work so that would be very much appreciated!!

**Comment by ODAKAB** [comment]
https://github.com/jojo2357/Music-Discord-Rich-Presence/pull/29

**Comment by jojo2357** [comment]
#29
