### ISSUE TITLE
Custom album arts in clientdata/ seem to be associated to only 1 player at a time

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/Music-Discord-Rich-Presence#27]
I have 2 custom dat files in `clientdata/` folder (apart from the default ones). One for groove, and the other for musicbee.
Before Installing musicbee the album arts were correctly working with groove.

But after creating another dat file for musicbee with the same contents as the first line and the only change being on line 1 `music.ui=groove` to `musicbee`, the DRP console shows _"Album art not keyed"_.

After doing alot of hit and trials with different file names and contents, when i changed the 1st dat file's line 1 to `musicbee` the DRP console showed _"This is a good one, ;-)"_

<sub>(PS: apologies if it feels like im piling too many issues 😅 )</sub>

**Comment by jojo2357** [comment]
Aw man i just added a new feature to (hopefully) prevent it from rereading albums if they were already keyed **for the same player** but it appears that may not be the case :/. Ill look into it

**Comment by jojo2357** [comment]
Oh just asking but did you change the id as well? If you dont it would show up as playing groove when youre using musicbee so you have to upload it separately which is why the duplicate file would be ignored

**Comment by RoguedBear** [comment]
oh shoot! Yes, I did not change the application id in the dat file.
I was so lost in making sure the album art was displayed in the RPC I didn't pay attention that using musicbee would show _Playing Groove Music_
