### ISSUE TITLE
Change icon to be more distinct from Discord

### ISSUE THREAD

**Issue by Ghoelian** [jojo2357/Music-Discord-Rich-Presence#3]
I found myself confusing this program and Discord in the task bar pretty often, it'd be great if you could alter the image so we can more easily differentiate it from normal Discord. I've made an alternative icon myself (uploaded to my Google Drive since GitHub doesn't allow .ico files as attachments), although I doubt you'd be allowed to use it since it includes the Groove icon as well.

https://drive.google.com/file/d/16_Y3lzGGOxeIRM73dqYdWFU6NlmaiHj5/view?usp=sharing

**Comment by jojo2357** [comment]
Yeah I figured someone would request this at some point. I do like that alternate icon you came up with, so I'll get a release out soon with a new icon.

**Comment by jojo2357** [comment]
See realease 1.2.2
