### ISSUE TITLE
Problems with menu + shortcuts

### ISSUE THREAD

**Issue by jojo2357** [jojo2357/Music-Discord-Rich-Presence#30]
as pointed out in the #29 thread, the new menu is buggy. Heres what doesn't work:
0: doesnt create shortcuts
1: doesnt launch mdrp
4-7: allegedly does not work with spaces (has not been replicated by me yet)

**Comment by jojo2357** [comment]
0 and 1 can be fixed quite easily but i need more information for 4-7

**Comment by RoguedBear** [comment]
> i need more information for 4-7

In trying to get some more logs, I used `LinkWithGroove` as a reference. narrowed it down to the batch file
 - the batch file ran perfectly via **command line**
 - double clicking on it results in the "spaces in path" problem  <details><summary>error:</summary><br>`'D:\Portable' is not recognized as an internal or external command,
operable program or batch file.` 
the repository's absolute path is: `D:\Portable Program Files\GroovyRichPresence\`</details>

**Comment by RoguedBear** [comment]
### Running via admin command line:
![2021-03-25-18-22-08-Trim](https://user-images.githubusercontent.com/39442192/112476200-aa335100-8d97-11eb-9451-4fa6bd6c4bcf.gif)

### Running by double-clicking on the batch file
![2021-03-25-18-17-37-Trim](https://user-images.githubusercontent.com/39442192/112476207-abfd1480-8d97-11eb-87d7-3d6595a9075c.gif)

**Comment by jojo2357** [comment]
Ok this is wild. Smaltin replicated the issue but I cannot even after downloading 1.4.4 from the releases and putting it in a spaced directory it still works nominally so this will be a tough one to fix...

**Comment by jojo2357** [comment]
@RoguedBear @Smaltin please verify most recent commit

**Comment by RoguedBear** [comment]
@jojo2357 I have verified the new commit 02661dbd723f615471921218e4fceab44a7d01d5,the bat file is working when double clicking and same for the shortcuts and launching from the MDRP Launcher.

**Comment by jojo2357** [comment]
Wooo! closing this. 1.5.0 will come out soon along with a mdrpl update
