### ISSUE TITLE
DRP doesn't launch automatically when I open MusicBee

### ISSUE THREAD

**Issue by rajanizara** [jojo2357/Music-Discord-Rich-Presence#33]
So i followed your instructions and the DRP works perfectly (the status shows album art, track title and artist name as expected) but won't launch when MusicBee opens, I have to run manually DRP in order to get MusicBee displayed on my Discord profile.
If the linking did not work, you said to unlink DRP and redo the installation, but it did not work for me :/

**Comment by jojo2357** [comment]
When you ran the linker, did it tell you the location of MusicBee? I am unable to replicate this issue. One thing that might shed light on the underlying issue would be to run the command line command 
`schtasks /query /tn MusicBeeRichPresenceOpen /XML`
which should give some output like this:
```XML
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Version>1.1.0</Version>
    <Date>2021-10-11T13:21:17-08:00</Date>
    <Author>jojo2357</Author>
    <Description>Runs DRP for MusicBee in the background when MusicBee is opened</Description>
    <URI>\MusicBeeRichPresenceOpen</URI>
  </RegistrationInfo>
  <Principals>
    <Principal id="Author">
      <UserId></UserId>
      <LogonType>InteractiveToken</LogonType>
    </Principal>
  </Principals>
  <Settings>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
  </Settings>
  <Triggers>
    <EventTrigger>
      <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="Security"&gt;&lt;Select Path="Security"&gt;*[System[Provider[@Name='Microsoft-Windows-Security-Auditing'] and Task = 13312 and (band(Keywords,9007199254740992)) and (EventID=4688)]] and *[EventData[(Data='C:\Program Files (x86)\MusicBee\MusicBee.exe')]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
    </EventTrigger>
  </Triggers>
  <Actions Context="Author">
    <Exec>
      <Command>C:\MDRPStuff\GroovyRP\bin\Release\RunHidden.vbs</Command>
    </Exec>
  </Actions>
</Task>```

From what I can tell, it wont start on battery (that might be your issue, if so, try while charging).

**Comment by rajanizara** [comment]
The first time I linked MusicBee I was indeed asked for the location. It worked normally and after I got my problem. When unlinking and relinking MusicBee, the program does not ask the location anymore, it finds musicbee.exe automatically.

I ran your command and I got 2 differencies with your text :
Line 12 : <UserId>S-1-5-21-2050646638-811656130-935151240-1002</UserId>
Line 28 : […] [EventData[(Data='cessus :    C:\Program Files (x86)\MusicBee\MusicBee.exe')]] […]
Maybe is the «cessus» the proof of any bug ?

I'm on a tower PC so we can skip the charging problem I guess

**Comment by jojo2357** [comment]
Yeah that is really strange I have no idea why that is there because it shouldnt be...

Please confirm that `LinkWithMusicBeept1.xml`, `musicbeelocation.dat`, and `LinkWithMusicBeeOpen.xml` do not contain this extra bit. if they do, remove it and then from that directory run the command `schtasks /create /tn MusicBeeRichPresenceOpen /XML LinkWithMusicBeeOpen.xml`

You can do the same thing with `LinkWithMusicBeeClose.xml` but please do inform me of what you do because I have never seen this issue before.

**Comment by rajanizara** [comment]
LinkWithMusicBeeOpen.xml and musicbeelocation.dat were containing this «cessus» so I deleted it (the third file did not have it).
I ran a command prompt and entered your command, the result is a error as shown in my screenshot (denied access despite I ran the prompt as an admin).
LinkWithMusicBeeClose.xml also contained a «cessus», I deleted it and I ran again a prompt then I got the same error.

**Comment by jojo2357** [comment]
Okay you can instead run the linker now since you should have fixed the problem. (no clue what caused it) The "automatic" part you found out about earlier will just pull from `musicbeelocation.dat` so you dont have to mess with the command line. Make sure you run the unlinker first before creating the shortcuts because it wont be able to create a task that already exists.

**Comment by rajanizara** [comment]
Oh yes it works perfectly, MusicBee is detected in Discord, big thanks !
NB : I tried to reinstall MDRP and the same problem occured, when detecting MusicBee the prompt says «the program is at cessus : C:/…» and I had to delete manually this word because it went in program files

Here in the screenshot that did not shown :
![erreur](https://user-images.githubusercontent.com/53912802/116534811-4d214280-a8e3-11eb-8b1a-0b9c7f322df9.png)
