### ISSUE TITLE
Unable to use in other drives

### ISSUE THREAD

**Issue by Anfeket** [jojo2357/Music-Discord-Rich-Presence#35]
Well, I think I can't link Groovy in my E: drive. Not sure what is the problem but I saw it is probably looking for Groovy in my E: drive too.
`set directory=%~dp0
Pushd %directory%` at GroovyRP\bin\Release\FindGroove.bat
Also, it doesn't continue after one of these lines, didn't get to see `echo I need to find the location of groove music on your computer, and the easiest way to do that is to open it and see where it came from`

**Comment by jojo2357** [comment]
What line does the program stop executing on? If you know how, please add print statements and let me know what the absolute directory is. Is there any other strange hardware setup that may be preventing this from working? Does it work on a different drive or none of your drives?

**Comment by Anfeket** [comment]
Ok, I'll try adding the print statements (did you mean echo? I'll try adding those) and about the location. It's on my 3rd E: drive (C: Windows, D: and E: as my game/personal storage). I don't think I have anything special set up tho. Didn't try it on D: since I don't really use it, it serves as backup. But after trying it worked on my C: drive so I think the problem is that it's trying to find groove on my E: drive where I'm running it from. I'll reply again when I get home and add the prints.

**Comment by Smaltin** [comment]
>I think the problem is that it's trying to find groove on my E: drive where I'm running it from. I'll reply again when I get home and add the prints.
I have MusicBee running on my D: drive (not my system drive) and it links just fine so it could be your filepath. I'd say give the full file path (you can cut your username out if you want) as @jojo2357 said previously.

**Comment by Anfeket** [comment]
So, I have the app at E:\Iné veci\Groovy DcRp (README.MD and other directories are here). Also added these lines to the linker:
``` @echo off
echo 1
set directory=%~dp0
echo 2
Pushd %directory%
echo 3

set "params=%*"
echo 4
cd /d "%~dp0" && ( if exist "%temp%\getadmin.vbs" del "%temp%\getadmin.vbs" ) && fsutil dirty query %systemdrive% 1>nul 2>nul || (  echo Set UAC = CreateObject^("Shell.Application"^) : UAC.ShellExecute "cmd.exe", "/k cd ""%~sdp0"" && %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs" && "%temp%\getadmin.vbs" && exit /B )
echo 5

echo I need to find the location of groove music on your computer, and the easiest way to do that is to open it and see where it came from
echo 6
```
looks like after few tests (it started asking for admin perms too fast) it stops at 4, then if I give it admin then it just prints this:
![image](https://user-images.githubusercontent.com/83760348/117510327-2bcbf080-af8c-11eb-89b9-d758322abbf7.png)
OH NEVERMIND, I just ran the linker itself with admin perms and it got to the linking process. I'm a genius.
nvm, after continuing it gave this:
![image](https://user-images.githubusercontent.com/83760348/117510475-6b92d800-af8c-11eb-8705-83ba85d7a158.png)
rough translation: file system error (errorcode) then this:
![image](https://user-images.githubusercontent.com/83760348/117510554-91b87800-af8c-11eb-9604-c690e36d58af.png)
then it just closed, not sure what is the problem then. I also recommend making the linker start with admin perms.
After trying to link with Music_drp_launcher.bat it has made the scheduled tasks but didn't show the RP on discord and the drp shows this:
![image](https://user-images.githubusercontent.com/83760348/117510918-35098d00-af8d-11eb-9603-51a83dbcec07.png)
tried with groove open and closed, linked and unlinked, same response.
That's all I could do to help, gotta make up for my sleep deprivation from the school days.

**Comment by jojo2357** [comment]
Okay so a few things. 

The line `cd /d "%~dp0" && ( if exist "%temp%\getadmin.vbs" del "%temp%\getadmin.vbs" ) && fsutil dirty query %systemdrive% 1>nul 2>nul || (  echo Set UAC = CreateObject^("Shell.Application"^) : UAC.ShellExecute "cmd.exe", "/k cd ""%~sdp0"" && %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs" && "%temp%\getadmin.vbs" && exit /B )
` is *supposed* to ask for admin perms so your recommendation is already there, however if there is a filesystem issue then it wont work which it appears there are.

The "Detected volume` message just means nothing is playing in groove so unless something *was* playing, I wouldnt be concerned.

So i went back and I guess u can try this less awesome groove finder (replace your `FindGroove.bat`):
```@echo off

set directory=%~dp0
Pushd %directory%

set "params=%*"
cd /d "%~dp0" && ( if exist "%temp%\getadmin.vbs" del "%temp%\getadmin.vbs" ) && fsutil dirty query %systemdrive% 1>nul 2>nul || (  echo Set UAC = CreateObject^("Shell.Application"^) : UAC.ShellExecute "cmd.exe", "/k cd ""%~sdp0"" && %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs" && "%temp%\getadmin.vbs" && exit /B )

echo I need to find the location of Groove on your computer, and the easiest way to do that is to open it and see where it came from

echo Checking admin rights...
net session 1>nul 2>nul

if not '%ERRORLEVEL%'=='0' (
echo Admin rights not detected. Please run with admin perms
pause
EXIT /B
)

auditpol /set /category:{6997984C-797A-11D9-BED3-505054503030} /success:enable>nul

taskkill /im Music.UI.exe 1>nul 2>nul

echo Please ensure Groove is closed then reopen it. once you have, reopen groove and then come back here and press any key to continue
pause>nul

wevtutil qe Security /c:200 /f:text /rd:true /q:"*[System[(EventID=4688)]]">openedfiles.dat

findstr /i "Music.UI.exe" openedfiles.dat>filelocation.dat

set /p loc=<filelocation.dat

echo Groove is at %loc:~19%

set /a "result=%result%-19"

call set parsed=%loc:~19%

rem debug echo %parsed%

set /p fgiddle=<fdoogle.dat

>filelocation.dat (
echo|set /p="%parsed%%fgiddle%"
)

taskkill /im Music.UI.exe 1>nul 2>nul

del openedfiles.dat 1>nul 2>nul

if "%parsed%"=="~19" (
echo TASK FAILED. please run me again and make sure that Groove is closed when you start me.
) else (
echo task completed. Please close Grooveidk y it didnt close on its own
)

pause```

That will link the same way musicbee does which requires some more user input :/. If that works then ill look into some possible changes but not exactly sure if it will in fact work

**Comment by Anfeket** [comment]
So after running your version of the linker I got to this (opened without admin):
![image](https://user-images.githubusercontent.com/83760348/117538575-1c3dbd80-b007-11eb-8a89-c47176750e95.png)
then it asked for admin and did this:
![image](https://user-images.githubusercontent.com/83760348/117538589-2b247000-b007-11eb-9d21-681984b0fa45.png)
Not sure what it did but here it is.

After opening the linker with admin it did this:
```

C:\Windows\system32>set directory=E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release\

C:\Windows\system32>Pushd E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release\

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>set "params="

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>cd /d "E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release\"   && (if exist "C:\Users\Anfeket\AppData\Local\Temp\getadmin.vbs" del "C:\Users\Anfeket\AppData\Local\Temp\getadmin.vbs"  )  && fsutil dirty query C:   1>nul 2>nul  || (echo Set UAC = CreateObject("Shell.Application") : UAC.ShellExecute "cmd.exe", "/k cd ""E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release\"" && E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release\FindGroove.bat ", "", "runas", 1   1>>"C:\Users\Anfeket\AppData\Local\Temp\getadmin.vbs"  && "C:\Users\Anfeket\AppData\Local\Temp\getadmin.vbs"   && exit /B  )

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>echo I need to find the location of Groove on your computer, and the easiest way to do that is to open it and see where it came from
I need to find the location of Groove on your computer, and the easiest way to do that is to open it and see where it came from

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>echo Checking admin rights...
Checking admin rights...

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>net session  1>nul 2>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>if not '0' == '0' (
echo Admin rights not detected. Please run with admin perms
 pause
 EXIT /B
)

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>auditpol /set /category:{6997984C-797A-11D9-BED3-505054503030} /success:enable 1>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>taskkill /im Music.UI.exe  1>nul 2>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>echo Please ensure Groove is closed then reopen it. once you have, reopen Groove and then come back here and press any key to continue
Please ensure Groove is closed then reopen it. once you have, reopen Groove and then come back here and press any key to continue

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>pause1>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>wevtutil qe Security /c:200 /f:text /rd:true /q:"*[System[(EventID=4688)]]" 1>openedfiles.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>findstr /i "Music.UI.exe" openedfiles.dat 1>filelocation.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>set /p loc= 0<filelocation.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>echo Groove is at C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe
Groove is at C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>set /a "result=-19"

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>call set parsed=C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>rem debug echo C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>set /p fgiddle= 0<fdoogle.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>(echo | set /p="C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe')]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;" ) 1>filelocation.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>taskkill /im Music.UI.exe  1>nul 2>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>del openedfiles.dat  1>nul 2>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>if "C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe" == "~19" (echo TASK FAILED. please run me again and make sure that Groove is closed when you start me. )  else (echo task completed. Please close Grooveidk y it didnt close on its own )
task completed. Please close Grooveidk y it didnt close on its own

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>pause
Press any key to continue . . .
```
probably because of `@echo off` not being there but at least there's more info.
```
E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>pause1>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>wevtutil qe Security /c:200 /f:text /rd:true /q:"*[System[(EventID=4688)]]" 1>openedfiles.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>findstr /i "Music.UI.exe" openedfiles.dat 1>filelocation.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>set /p loc= 0<filelocation.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>echo Groove is at C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe
Groove is at C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>set /a "result=-19"

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>call set parsed=C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>rem debug echo C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>set /p fgiddle= 0<fdoogle.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>(echo | set /p="C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe')]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;" ) 1>filelocation.dat

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>taskkill /im Music.UI.exe  1>nul 2>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>del openedfiles.dat  1>nul 2>nul

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>if "C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe" == "~19" (echo TASK FAILED. please run me again and make sure that Groove is closed when you start me. )  else (echo task completed. Please close Grooveidk y it didnt close on its own )
task completed. Please close Grooveidk y it didnt close on its own

E:\Iné veci\Groovy DcRp\GroovyRP\bin\Release>pause
Press any key to continue . . .
```
Then this after opening and closing Groove several times, I think it found it.
After using the linker it linked Groove, there weren't any problems except I had to run it with admin perms.
Had the same problem as here:
![image](https://user-images.githubusercontent.com/83760348/117538589-2b247000-b007-11eb-9d21-681984b0fa45.png)
After closing Groove (I ran the linker with Groove open) I got this when it closed:
![image](https://user-images.githubusercontent.com/83760348/117539044-f6b1b380-b008-11eb-979b-1c1c2ce66f7b.png)
It's probably a bug since I have an é in the path and it didn't save properly. (It didn't) After looking at LinkWithGroove.xml I found this:
```
<?xml version="1.0" ?>
<!--
This sample schedules a task to start notepad.exe at a specific time.
-->
<Task xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
    <RegistrationInfo>
        <Date>2021-10-11T13:21:17-08:00</Date>
        <Author>jojo2357</Author>
        <Version>1.0.0</Version>
        <Description>Kills DRP for Groove when groove is closed</Description>
    </RegistrationInfo>
    <Triggers>
        <EventTrigger>
            <Enabled>true</Enabled>
            <Subscription>
                &lt;QueryList&gt;&lt;Query Id="0" Path="Security"&gt;&lt;Select Path="Security"&gt;*[System[Provider[@Name='Microsoft-Windows-Security-Auditing'] and Task = 13313 and (band(Keywords,9007199254740992)) and (EventID=4689)]] and *[EventData[(Data='C:\Program Files\WindowsApps\Microsoft.ZuneMusic_10.20122.11121.0_x64__8wekyb3d8bbwe\Music.UI.exe')]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;            </Subscription>
        </EventTrigger>
    </Triggers>
    <Principals>
        <Principal id="Author">
            <RunLevel>LeastPrivilege</RunLevel>
        </Principal>
    </Principals>
    <Settings>
        <Enabled>true</Enabled>
        <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
        <AllowStartOnDemand>true</AllowStartOnDemand>
        <AllowHardTerminate>true</AllowHardTerminate>
    </Settings>
    <Actions>
        <Exec>
            <Command>
E:\In‚ veci\Groovy DcRp\GroovyRP\bin\Release\KillHidden.vbs
            </Command>
        </Exec>
    </Actions>
</Task>
```
I have unlinked Groove (had the same problems without admin perms) and it changed the path back to In, veci so I fixed it again.
After linking and checking the path in the task scheduler and during writing this sentence I got this:
![image](https://user-images.githubusercontent.com/83760348/117539044-f6b1b380-b008-11eb-979b-1c1c2ce66f7b.png)
Didn't even open or close Groove, not sure what triggered it. I have fixed the path directly in the task scheduler.
Also, after fixing it I noticed it didn't save it with quotation marks so that could be a problem for paths with a space in them.
It didn't run automatically but after running RunHidden.vbs manually it worked and showed on Discord.
Also after closing Groove, I had to choose what to open something with, I suppose it was KillHidden.vbs so I closed the popup and did it manually. Also added run with highest privileges to make sure it would work.
After opening Groove it asked again what to open with even though I don't know what.
I looked on the internet about the problem and probably found a solution [here](https://stackoverflow.com/questions/21176656/running-visual-basic-script-as-a-scheduled-task-asks-how-i-want-to-open-the-file) and followed the steps.
It worked though but it wasn't hidden anymore so I found a better solution [here](https://superuser.com/a/1113550).
Works like a charm.

Here's a small rundown:
- Updated the finder - previous reply
- linker used the wrong path - é wasn't saved properly
- scheduled task couldn't open the .vbs files - used wscript.exe with arguments
It works well now, the only thing I recommend is replacing the task scheduler files (LinkWithGrooveOpen/Close.xml) to save it with wscript.exe and the Groove location as arguments and support for characters like é but that was probably a bug on my side.
The finder could probably be replaced with this one but made a bit more user-friendly. At least it works now. Thanks for helping though, this project is pretty cool. Hope it works well!

**Comment by jojo2357** [comment]
Awaiting another user to have this error since I cannot replicate and will take a lot of effort to fix. Closing for now since there are workarounds
