### ISSUE TITLE
For some reason, album art is not showing up...

### ISSUE THREAD

**Issue by LyingJay** [jojo2357/Music-Discord-Rich-Presence#42]
I am on release 1.5.5
The album art works for every single song, including new songs that I have added, all except for 1 song.
I have attempted to resolve the issue several times, and also ensured that the title in discord assets and the .dat file are correct.

Here's the song in Groove, so you can see the title and image.
![image](https://user-images.githubusercontent.com/78644149/121656273-a8e60a80-cae2-11eb-9273-719268280b41.png)
Here's the image uploaded to discord assets.
![image](https://user-images.githubusercontent.com/78644149/121656394-c87d3300-cae2-11eb-88be-91ccab8f0a5b.png)
Here's the .dat file (In text format bc i can't upload .dat files) and a screenshot of the line in the file (it's near the very bottom).
![image](https://user-images.githubusercontent.com/78644149/121656476-dcc13000-cae2-11eb-89c5-2deb45cd5334.png)
[stuff.txt](https://github.com/jojo2357/Music-Discord-Rich-Presence/files/6636970/stuff.txt)

Keep in mind that it is only for this song that DRP doesn't work, and I'm not sure why. I swear if it is actually a typo that I am blind.

**Comment by LyingJay** [comment]
Forgot to add, here's what it looks like in discord:
![image](https://user-images.githubusercontent.com/78644149/121657185-886a8000-cae3-11eb-9202-90926304464c.png)
meanwhile you would expect something like 
![image](https://user-images.githubusercontent.com/78644149/121657459-c49de080-cae3-11eb-9b62-429f7ee19776.png)

but to me, all the syntax and stuff I've provided in the original post seems correct, and i've followed the same steps as I have done for other songs, so it's strange to me why it doesn't work when it seems like it should.

**Comment by Smaltin** [comment]
Please check your key again, I replicated the issue but putting a different key seemed to work with the same album.

**Comment by LyingJay** [comment]
The key is correct. Since every other song works, the key should be correct. I also double checked that it matches.
![image](https://user-images.githubusercontent.com/78644149/121660495-aa193680-cae6-11eb-9347-ba11d9d3a725.png)
you can also check this with the text file.

**Comment by Smaltin** [comment]
Have you tried keying it under a different key?

**Comment by LyingJay** [comment]
sorry, how would i go about doing that? would it involve creating a new discord application and uploading all album images to it again?

**Comment by jojo2357** [comment]
No he is asking if you change the name in the dat file to be an image that works already, will it show up as that image?

**Comment by LyingJay** [comment]
oooh, apologies. ty for clearing that up
I changed it to this:
![image](https://user-images.githubusercontent.com/78644149/121766685-3125e780-cb97-11eb-81e9-e056f7e98117.png)
and still no image.

**Comment by LyingJay** [comment]
Update: Interestingly, when i change it to this:
![image](https://user-images.githubusercontent.com/78644149/121768168-1dcb4a00-cba0-11eb-9a74-8d8665533fa7.png)
The image appears in DRP (of course, for the wrong song)
![image](https://user-images.githubusercontent.com/78644149/121768178-320f4700-cba0-11eb-9925-5cc608bdc6b1.png)
but no matter what image I assign to ロメオとシンデレラ, the image will not show up
![image](https://user-images.githubusercontent.com/78644149/121768202-5408c980-cba0-11eb-9098-9aee71298804.png)
Hope this helps

**Comment by Smaltin** [comment]
I just noticed `ロミオとシンデレラ==romeoandcinderella` inside your file. This is not a valid key, and therefore doesn't work.

**Comment by LyingJay** [comment]
🤦‍♂️ can’t believe I didn’t see that. Thanks so much for pointing it out to me and helping me

**Comment by jojo2357** [comment]
It's about time that I make a file validation tool since MDRP has consistently stood up to a handful of "issues" (im not blaming anyone, if you dont use the [library tool](https://github.com/jojo2357/Music-Discord-Rich-Presence-Library) it would be very hard to create valid files).

**Comment by jojo2357** [comment]
Using the new [validation tool](https://jojo2357.github.io/MDRP-Validation-Tool/) yields the following console output on your dat file:

```
Run Output for stuff.txt: 
ID: 813003117771096064
    WARNING line 89 the ablum "ロミオとシンデレラ" has a key ("romeoandcinderella") that could not be found in the assets uploaded to discord.
    WARNING line 96 duplicate album found: "ロミオとシンデレラ" is found more than once.
```

which makes the whole problem super easy to fix. sorry i didnt have this earlier it only took me an hour to make it 😔
