### ISSUE TITLE
MDRP fails to display rich presence after About Me discord update

### ISSUE THREAD

**Issue by LyingJay** [jojo2357/Music-Discord-Rich-Presence#43]
**Version**
The version the bug was found on: 1.5.5

**Describe the bug**
Rich presence no longer shows up, even though MDRP says that everything is valid in windowed mode.

**To Reproduce**
1. Install MDRP and set up as usual, locating Groove and linking.
2. Run MDRP (windowed or hidden) when Discord and Groove are open
3. No Rich Presence is shown

**Expected behavior**
I expected the usual MDRP rich presence to show up, with the application name, album art, song title, song artist (although this issue is not about album art).

**Screenshots**
Here's MDRP windowed, and the Discord profile:
![image](https://user-images.githubusercontent.com/78644149/125378239-bb00e480-e3d1-11eb-813e-3afb064e04a7.png)

**Additional context**
I believe it could possibly be due to the new 'About Me' feature that discord released. Maybe that affects the way rich presence works somehow? But it no longer works for me, even when I remove About Me. I already tried reinstalling MDRP as well, after removing About Me and restarting discord.
I'm wondering if this is something on my end, or whether MDRP is not working on the latest versions of discord. Apologies again if it's something on my end :)

**Comment by Smaltin** [comment]
Are you sure Game Activity is turned on? (Settings > Activity Status)
![image](https://user-images.githubusercontent.com/6719266/125382302-4a62b500-e34a-11eb-9555-dedf8e44448a.png)

**Comment by LyingJay** [comment]
ok, that fixed it!
strange though, i don't remember ever turning it off
apologies for giving annoying issues that have easy solutions, lol, but thanks for the help as always!

**Comment by Smaltin** [comment]
No problem, it just gives us a issue to refer others to when they run into the issue so you're doing us a service in the end :+1:
