### ISSUE TITLE
Add app support for the New Windows Media Player in Windows 11

### ISSUE THREAD

**Issue by BearTS** [jojo2357/Music-Discord-Rich-Presence#50]
Add support for the new Windows Media Player introduce in Windows 11

**Comment by jojo2357** [comment]
I was waiting for someone to mention this. I dont have windows 11 but ill get on it and get a release out this week probably.

**Comment by BearTS** [comment]
ooh alright, if you don't feel like upgrading, ypu can surely make use of VM. 
Also installing the new Media Player has to done manually by making some changes if on stable release of win 11
Lemme know if you get issues once you get windows 11

**Comment by jojo2357** [comment]
haha @Smaltin has Win 11 so he will probably be the one to make 1.6.2, but I'll nag him ;)

**Comment by BearTS** [comment]
Also, uh don't know if there is something wrong w my device. 
I couldn't open the hidden version of DRP and neither the schedule works for me (linking to groove)
Could be Windows 11? or prolly something else wrong

**Comment by Smaltin** [comment]
The schedule will not work as groove is no longer the music application. As for launching hidden, I will look into this

**Comment by jojo2357** [comment]
The hidden thing was a problem I encountered with the MB plugin, where with the win11 environment it just isnt possible to launch a program in the background? At least i didnt find a way in c#...

**Comment by BearTS** [comment]
> The schedule will not work as groove is no longer the music application. As for launching hidden, I will look into this

What do you mean by "groove is no longer the music application"

**Comment by jojo2357** [comment]
It is a new app and the linker is configured for groove which it isnt called anymore, its a behind the scenes thing

**Comment by BearTS** [comment]
Oh I see alright, but can't it be easily fixed?

**Comment by jojo2357** [comment]
Yeah it should be relatively easy, just gotta go through the motions of figuring out the new stuff.

**Comment by BearTS** [comment]
Can you guys add support to foobar as well?

**Comment by jojo2357** [comment]
It turns out that foobar is actually really hard to integrate. WMC doesnt have the album tied into it, and i havent had the time to learn the new c++ plugin environment. If you would like, i can write the short requirements for a plugin to integrate with mdrp. I dont have as much time as i would like to have right now so the help of others would be appreciated.

**Comment by BearTS** [comment]
aah in that case, its no worries
do it whenever you have time :)
