### ISSUE TITLE
Custom Play and Pause icon pictures.

### ISSUE THREAD

**Issue by darthdemono** [jojo2357/Music-Discord-Rich-Presence#55]
I think there should be a custom play and pause small icon picture in The Discord Rich Presence.

A custom play and pause icon pictures should be implemented so that rather than having the same icon of the Music player on both of the Small and Large Images when we don't key an album on the songs.dat file, we can customize it to anything we like as the default small icon of the Rich Presence is the music player.

Playing a unkeyed Album: 
![💬﹚adda-chat - Discord 12_25_2021 09_44_55 PM](https://user-images.githubusercontent.com/64983290/147388631-bce241b7-a9df-4012-84f0-3dec73cf9920.png)
Paused unkeyed Album 
![💬﹚adda-chat - Discord 12_25_2021 09_45_04 PM](https://user-images.githubusercontent.com/64983290/147388633-1b5db31c-8159-47dd-8b6b-2008a0b6209c.png)

Playing Keyed Album: 
![💬﹚adda-chat - Discord 12_25_2021 09_54_43 PM](https://user-images.githubusercontent.com/64983290/147388812-1e2e63fb-9cd1-4a90-8f3d-59917d938d79.png)

Paused Keyed Album: 
![💬﹚adda-chat - Discord 12_25_2021 09_56_49 PM](https://user-images.githubusercontent.com/64983290/147388877-d52af08f-7085-4111-b847-545e02bca23a.png)

I want to be able to customize the small pause icon. A play Icon is not needed but, a feature to customize it will be helpful.
I also want to be able to show the paused icon when the player is paused.

**Comment by jojo2357** [comment]
Already implemented. To do, upload an asset named `paused` for the paused small icon, for small play icon, the name of the asset is the player name followed by `_small` so `musicbee_small` or `groove_small`. 

The default background for an unkeyed album can be changed by changing the default app to your own app and uploading an asset with the player name like `musicbee` or `groove`

**Comment by darthdemono** [comment]
Thanks, It's very useful. I forgot to read the Readme as I updated it from 1.6.0. Thank you for your time..
