### ISSUE TITLE
not working :(

### ISSUE THREAD

**Issue by kryparnold** [jojo2357/Music-Discord-Rich-Presence#57]
its not showing music on the terminal so not showing on the discord too. im using groove music

**Comment by jojo2357** [comment]
See #56

This is a newer problem and I have no clue why it is happening.

**Comment by jojo2357** [comment]
I have a beta version of 1.6.3 i woul like you to test, please [join my discord server](https://discord.gg/qVbY2ygeGy) and request a demo version there that will hopefully resolve your issue
