### ISSUE TITLE
Title and Artist do not display on 1.7.0

### ISSUE THREAD

**Issue by ORIOLESFan02** [jojo2357/Music-Discord-Rich-Presence#62]
**Version**
The version the bug was found on: 1.7.0

**Describe the bug**
Music doesn't seem to update. Usually gets stuck on one song, or it gets stuck saying 
`Title:`
`Artist: Unknown Artist`
I usually have to restart Windows Media Player for this to work, but the same problem keeps happening and I don't understand why or how since it's never done this before until today. 

While typing this, I just noticed a new thing, some songs will not show, but others like Bohemian Rhapsody for example will show.
![Discord_VF4SL6T8wu](https://user-images.githubusercontent.com/48143202/167269334-098263e2-d628-434f-85a1-938517736acd.png)

**To Reproduce**
1. Go to '1.7.0_Release folder' (Assuming that you already downloaded it)
2. Click on 'Music_DRP_Launcher.bat' and hit '1 or 2'
3. Scroll down to 'Music Details'
3.5 The thing that may happen is that the first one may show, but the song after that may not. My recommendation would be to play a couple songs if you want to test this out as well.

**Expected behavior**
All the songs are supposed to show no matter the song name and/or album name.
I could care less about the Album Cover, but I do know that's already in the application since I read the readme and the changelog or whatever it's called.

**Screenshots**
![MDRP_6xnEo6z1mq](https://user-images.githubusercontent.com/48143202/167269182-49fab04d-ce72-4ca7-8d9c-b8ead622033d.png)
![Discord_iaznHIkpEr](https://user-images.githubusercontent.com/48143202/167269194-d1f969ac-89be-4aeb-896d-26befb0baa8d.png)

**Additional context**
I was messing with the ini file so that could also be my fault, but I would like to hear what you (the dev) and others (the community) have to say about this problem. I hope this makes sense since I'm not the best at explaining things and I hope you have a good one. 
Thanks!

**Comment by jojo2357** [comment]
I see in one of your screenshots a bug that I have noticed and am planning to fix, where paused music doesnt display the background, but the paused icon takes over.  Maybe this is somehow related? Not sure, but maybe others can corroborate this for me? 

Do you mean that the display in discord gets stuck, the console gets stuck, or both get stuck on certain media? Also does this happen only on specific songs, or does this have a chance of happening on any song? Do these songs have anything in common? When I get the chance I will look into it, thanks for your patience

**Comment by ORIOLESFan02** [comment]
> I see in one of your screenshots a bug that I have noticed and am planning to fix, where paused music doesnt display the background, but the paused icon takes over. Maybe this is somehow related?

Honestly, that wasn't my main concern, they could be related, but I didn't want the song to go over, so I paused it. Sorry for the confusion

> Do you mean that the display in discord gets stuck, the console gets stuck, or both get stuck on certain media?

They both get stuck, and from what I saw, I thought it was every single song, but besides the Bohemian Rhapsody screenshot and without restarting WMP, I'm not entirely sure. I've seen it become a hit or miss, but it's becoming more of a miss than a hit if that makes sense.

> Do these songs have anything in common?

Most of the songs I listen to are either Classic Rock, Heavy Metal, or a couple odd balls that could go in either genre. That's the only thing they really have in common.

Once again, I'm not the best at explaining things, but if you don't understand some things that I just said, then don't hesitate to quote them and I'll try to elaborate further. _hopefully_

**Comment by jojo2357** [comment]
> Do these songs have anything in common?

Think about this from my perspective. Do they all have `Unknown Artist`? do they all have no name? Do they all have no album? what in the console do they have in common? 

Other question, is how does the music show up in WMC (Windows Media Center which is the thing that pops up when you change the volume, and will have the currently playing song on there usually)

**Comment by ORIOLESFan02** [comment]
Here's an updated screenshot to hopefully show you what I'm talking about.
The song is playing, but I didn't want to stretch the screenshot a lot, so I hope you understand.

![ApplicationFrameHost_EMczClG6IZ](https://user-images.githubusercontent.com/48143202/167270113-0958e127-33f0-4bab-ba6d-d185894fa6d9.png)

**Comment by ORIOLESFan02** [comment]
> Think about this from my perspective. Do they all have `Unknown Artist`? do they all have no name? Do they all have no album? what in the console do they have in common?

My mistake, not the greatest at understanding things. They all usually say nothing for the title and `Unknown Artist` in the Artist section

> Other question, is how does the music show up in WMC (Windows Media Center which is the thing that pops up when you change the volume, and will have the currently playing song on there usually)

![ApplicationFrameHost_7eQq57VNh8](https://user-images.githubusercontent.com/48143202/167270261-972bbafd-7cf1-4fb5-aab6-9b23cd3b6672.png)

**Comment by jojo2357** [comment]
Not there, something like this:
![image](https://user-images.githubusercontent.com/66704796/167270317-7d6dd6b5-e1cb-469d-9fcc-99a8c57d5346.png)

Unless win 11 broke everything, I am still on 10 so I am not too versed in all the changes

**Comment by ORIOLESFan02** [comment]
No, but that hasn't shown up for awhile since I updated to Windows 11 :/

![firefox_KVAbYwvJ4c](https://user-images.githubusercontent.com/48143202/167270349-5369c51f-cd1e-469d-bd65-49d04e6d55d7.png)

**Comment by jojo2357** [comment]
Ok let me check with @Smaltin to figure out how MDRP works at all in win 11 and if he can replicate it

**Comment by ORIOLESFan02** [comment]
> Ok let me check with @Smaltin to figure out how MDRP works at all in win 11 and if he can replicate it

Alright, sounds good.

**Comment by ORIOLESFan02** [comment]
Update: Seems like specific songs work for some reason.

![GPVifsl4Tx](https://user-images.githubusercontent.com/48143202/167270589-44127db9-0048-4b5e-b649-ae86e51225c0.png)

**Comment by jojo2357** [comment]
Could you privately send me one of your MP3s that breaks everything? You can DM me if you join [my discord](https://discord.gg/qVbY2ygeGy) or you can maybe send it here? I havent been able to replicate this issue with any of my media so maybe something is different with yours?

**Comment by ORIOLESFan02** [comment]
> Could you privately send me one of your MP3s that breaks everything? You can DM me if you join [my discord](https://discord.gg/qVbY2ygeGy) or you can maybe send it here? I havent been able to replicate this issue with any of my media so maybe something is different with yours?

Ok, I think I may know the problem. The problem may be because of the Album Artwork. I'll join your discord server and I'll send you two files. One song that has album artwork and another song without Album Artwork. This never happened before, but that's my conclusion.

**Comment by jojo2357** [comment]
Please see if this has improved in 1.7.1

**Comment by ORIOLESFan02** [comment]
> Please see if this has improved in 1.7.1
Some things happened and I don't use discord very often anymore. I may try, I may not. Just thought I would update you on the situation

**Comment by dolfies** [comment]
I'm having the same issue. Interestingly, with some messing around, I got media player to be detected as Groove and everything worked perfectly (until I restarted, and I was never able to do it again 😄).

**Comment by jojo2357** [comment]
It has been a while, we couldnt find the cause, and some time has passed so I will consider this resolved for now
