### ISSUE TITLE
Tidal does not work

### ISSUE THREAD

**Issue by iXlZZ** [jojo2357/Music-Discord-Rich-Presence#63]
Tidal player is meant to work with the played but isn't actually a thing in the config ini. When the tidal application id for discord is added (which was provided by jojo) it does work but doesnt display album art.

**Comment by jojo2357** [comment]
Thanks for your help, I have mostly figured it out, and in the meantime I will iron out more issues.

**Comment by jojo2357** [comment]
This was fixed as best as possible in 1.7.1.

**Comment by iXlZZ** [comment]
No problem. Glad to hear you’re making progress and im glad to use it if
and when it works.
