### ISSUE TITLE
MDRP does not detect Music playing in Groove or WMP

### ISSUE THREAD

**Issue by Nyrif** [jojo2357/Music-Discord-Rich-Presence#66]
**Version**
1.7.0

**Describe the bug**
MDRP says "Detected volume in something but not showing as it is not currently supported or is disabled", nothing appears on discord

**To Reproduce**
1. Run MDRP
2. Try to play anything on any of the supported programs
3. See "Detected volume in something but not showing as it is not currently supported or is disabled"

**Expected behavior**
It should of showed the rich presence on discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/30084485/169397178-cd9e9f71-8959-464e-aeb0-32f74101e7ab.png)

**Comment by jojo2357** [comment]
Can not reproduce; MDRP works for me in both groove and musicbee. Which players did you test?

**Comment by Nyrif** [comment]
Tried groove, musicbee, and WMP, none worked
Followed all the instructions in the readme, I don't think I set it up wrong

**Comment by jojo2357** [comment]
Musicbee wont work without [a plugin](https://github.com/jojo2357/MDRP-MusicBee-Bridge) to begin with, but did you change some audio settings on your device? What kind of device are you using? Do other programs malfunction? Do you actually hear any audio? Have you tried Spotify? What version of windows are you on? So many questions.

**Comment by Nyrif** [comment]
I hear audio playing just fine, never changed any audio settings. I'm on Windows 11, and I don't have spotify so I wasn't able to try that

**Comment by Nyrif** [comment]
I installed spotify and spotify works, it's just groove and wmp that don't

**Comment by jojo2357** [comment]
Did you change the config ini? Can you make sure that groove and wmp are enabled? Also it was my understanding that wmp replaced groove so how do you even still have it?

**Comment by Nyrif** [comment]
Groove and WMP are enabled, and groove was never removed, it's still in Windows 11

**Comment by jojo2357** [comment]
Thats wild that spotify works; did you recently update to a newer windows 11 version? Maybe @Smaltin can chime in?

**Comment by Nyrif** [comment]
I did update my PC recently, but it didn't say it was an actual windows 11 update, it said it was a chipset update

**Comment by jojo2357** [comment]
well if you have musicbee, I would try it again, with the plugin i mentioned before and see if that works. Hopefully it does, since I dont know anybody that can replicate you issue, and until then, I am going to assume it is a user-specific configuration issue. If musicbee *doesnt* work, then there are bigger issues at play

**Comment by Nyrif** [comment]
Musicbee works with the plugin installed, but I use WMP more than musicbee, I forgot I had musicbee for the longest time

**Comment by Nyrif** [comment]
It gives this error when WMP isn't even running, and there's no audio playing in any apps.

**Comment by jojo2357** [comment]
> It gives this error when WMP isn't even running, and there's no audio playing in any apps.

Yes, that is the expected behavior. Have you also tried running the debug exe? Maybe something is up there? If that doesnt tell you anything, could you join [my discord](https://discord.gg/qVbY2ygeGy) so i can send you a debug version of MDRP for testing?

**Comment by Nyrif** [comment]
I've tried running the debug exe and it shows nothing

**Comment by jojo2357** [comment]
Privately, Nyrif and I narrowed down the issue to one of either their WMP having changed their process name to `wmplayer` (formerly `microsoft.media.player`) and/or WMP not registering the audio that it is playing in WM**C**, and thus being invisible to MDRP. 

This means there is **no possible fix** without more information on the user setup that may be negatively impacting WMP's ability to register its media on the `GlobalSystemMediaTransportControlsSessionManager` (aka WMC).

**Comment by Nyrif** [comment]
It works on a VM, so it's an issue with my windows install.

**Comment by Nyrif** [comment]
Windows broke my audio driver, reinstalling the audio driver fixed it.
