### ISSUE TITLE
[Suggestion] Amazon Music

### ISSUE THREAD

**Issue by Social-Interactive** [jojo2357/Music-Discord-Rich-Presence#68]
Please add Amazon Music to the supported platforms<3

**Comment by jojo2357** [comment]
Could you please join [my discord](https://discord.gg/qVbY2ygeGy) so i may send you a testing version of MDRP so we can determine if it is possible to add Amazon Music? I tried testing it a while back, but unfortunately it required payment so I never tested it fully (iirc)

**Comment by jojo2357** [comment]
There is support in 1.7.2, but you will need to verify that it works for me since i dont know anybody with amazon music that can test it, but behind the scenes everything that is needed was added
