### ISSUE TITLE
[Suggestion] foobar2000 Support

### ISSUE THREAD

**Issue by aizuchan** [jojo2357/Music-Discord-Rich-Presence#69]
Could you add foobar2000 support? (✧ω✧)

Thank you for your time ;D

**Comment by jojo2357** [comment]
I was thinking about it, but i just dont have the time or motivation. In principle it would not be very hard, and i just dont want to go through the foobar sdk, i dont use the player so i find it hard to navigate, i already get enough headaches from WMC working sporadically, and i dont use mdrp anymore. If someone were interested, let me know and i can explain how to interface with mdrp.
