### ISSUE TITLE
Not too sure what to do here

### ISSUE THREAD

**Issue by Mantis03** [jojo2357/Music-Discord-Rich-Presence#70]
Detected volume in something but not showing as it is not currently supported or is disabled

What could this mean? Could it be happening because I have Groove running through Voicemeeter?
I have groove open, ran the batch file, selected the location of groove music. And after running MDP it gave me this error

![image](https://user-images.githubusercontent.com/81198680/177009411-1a4eed9b-f1d7-4964-84cf-3172d0ec3a29.png)

**Comment by jojo2357** [comment]
Yes im pretty sure that if you are piping the audio through another app that mdrp will think that app is playing music instead of groove. Try disabling it and playing straight out of groove.

**Comment by Mantis03** [comment]
I set them to just play through the default audio device (Just straight to my headphones) And i'm still getting the same error (This is also after a whole re/extract/install of the software)

**Comment by jojo2357** [comment]
Make sure the player is enabled in the settings file, restart mdrp, and if the issue persists, i cant be much more help for a few days since i am away from my windows computer. Mdrp has a nasty habit of inexplicably not working because the API it has to use is unreliable and i apologize for that. 

If you want it to work more reliably, i would recommend using MusicBee since there is a plugin that circumvents the windows api i mentioned.

**Comment by Mantis03** [comment]
I'll keep tinkering with it to see what else I could do. Thank you for the practically instant responses, I'll say something if I've managed to figure it out though. Again thanks a bunch!

**Comment by Mantis03** [comment]
After a bit of tinkering I figured it out, and its working flawlessly. Some steelseries software (That I used like 2 years ago) was taking full control of my audio outputs/inputs, after uninstalling that and linking everything up to what I wanted through voicemeeter and setting my Groove Music output as the default audio device, seemed to fix the issue..

**Comment by jojo2357** [comment]
What was the use of voicemeeter and does it work with it enabled or do u have to use default out?

**Comment by jojo2357** [comment]
Could you [join my discord](https://discord.gg/qVbY2ygeGy) and walk me through your voicemeeter setup so i can replicate your issue? i got audio running thru the meeter but MDRP still works (I can hear the music so i think i shouldnt but then how do i know it is playing?). I have a possible fix in mind but i have to cause the issue to test fixes

**Comment by jojo2357** [comment]
This should be fixed in 1.7.2. Please reopen if still having this issue
