### ISSUE TITLE
can you add amazon music support

### ISSUE THREAD

**Issue by Pickymarker** [jojo2357/Music-Discord-Rich-Presence#72]
can you add amazon music support

**Comment by jojo2357** [comment]
There already is, but nobody tested it for me, and I dont have access to it. Download 1.7.2 and in your ini, add `amazon music=true=807774172574253056`

This will not say `Amazon Music` in your rich presence, but if it otherwise works then I will make an app for it.

If adding that line and restarting doesnt work, then try changing `debug missing player` to `true` and see if MDRP can even detect it.

**Comment by Pickymarker** [comment]
it works it just shows up as groove muisc

**Comment by jojo2357** [comment]
Give me 5 minutes and I will have a fix for that

**Comment by jojo2357** [comment]
Okay, change `amazon music=true=807774172574253056` to `amazon music=true=808571949227049000`, and add 
```
small amazon music asset=https://cdn.discordapp.com/app-assets/808571949227049000/1011411659518136340.png
large amazon music asset=https://cdn.discordapp.com/app-assets/808571949227049000/1011411657114783774.png
```
and you should be good to go

**Comment by Pickymarker** [comment]
so like this 
![image](https://user-images.githubusercontent.com/74084396/186037080-6a423a1c-19c4-4039-92b0-e07a0d6d7715.png)
and which one do i select and what about album art and stuff 
![image](https://user-images.githubusercontent.com/74084396/186037160-d88c3d43-711f-4128-ba7e-3d33d39d77ca.png)

**Comment by jojo2357** [comment]
You didnt add 

```
small amazon music asset=https://cdn.discordapp.com/app-assets/808571949227049000/1011411659518136340.png
large amazon music asset=https://cdn.discordapp.com/app-assets/808571949227049000/1011411657114783774.png
```

and you should follow the readme for more instructions on other settings to change. you would probably want `get remote artwork`, but again, check the documentation.

**Comment by Pickymarker** [comment]
![image](https://user-images.githubusercontent.com/74084396/186037669-6ccb65b0-284e-4a10-b25e-b386d517cf46.png)
but the album art is not working

**Comment by jojo2357** [comment]
Did you restart MDRP, and in the console can you see that there is an album? or does it only show artist and title?

**Comment by Pickymarker** [comment]
it only shows artist and title and i keep getting the error Image could not be found remotely

**Comment by jojo2357** [comment]
thats because Amazon Music is not reporting the artist to Windows Media Center. There is nothing I can do to fix that without hacking Amazon Music which I am greatly disinterested in doing. 

Sorry for any inconvenience, but it might be better than nothing.
