### ISSUE TITLE
Played with icon and stuff in DiscordPresenceConfig.ini (Never again)

### ISSUE THREAD

**Issue by gadingprakasa** [jojo2357/Music-Discord-Rich-Presence#77]
So, I try to change icons that were used in DRP (such as paused icon) and it lead me to this 
![image](https://user-images.githubusercontent.com/118760184/203881570-efe61c9c-2850-4420-a524-ceef8852239c.png)

After I paste a new link for the icon, that thing happened. I just realize that those icons has "app-assets" as parent folder and kinda bump out since I don't save the old link. Is there a way to fix this?

**Comment by RoguedBear** [comment]
maybe you can get the old icons back by using the default app ids, in the default config file if that portion is what you changed in `DiscordPresenceConfig.ini`

https://github.com/jojo2357/Music-Discord-Rich-Presence/blob/3ad92d3dd6929cd4ce6a2ea93489700a83f01207/DiscordPresenceConfig.ini#L1-L6

**Comment by jojo2357** [comment]
Why did you edit the title? It sounds like Discord had an issue and it resolved itself. Please advise if you still have the issue. I am not really sure what you did to cause this error, so I hope it is better now.

Also good to see you RoguedBear :)

**Comment by gadingprakasa** [comment]
> maybe you can get the old icons back by using the default app ids, in the default config file if that portion is what you changed in `DiscordPresenceConfig.ini`
> 
> https://github.com/jojo2357/Music-Discord-Rich-Presence/blob/3ad92d3dd6929cd4ce6a2ea93489700a83f01207/DiscordPresenceConfig.ini#L1-L6

yup, turns out that i've open the icon link via browser before and managed to copy-paste it back to .ini file. thank you tho!

**Comment by gadingprakasa** [comment]
> Why did you edit the title? It sounds like Discord had an issue and it resolved itself. Please advise if you still have the issue. I am not really sure what you did to cause this error, so I hope it is better now.
> 
> Also good to see you RoguedBear :)

Idk why i edited the title xD But no, it's not repairing itself. The idea of customizing the icon would be really neat tbh. Thank you!

**Comment by jojo2357** [comment]
Oh, you can. I misunderstood. That link may not have been taken by discord (some domains don't work an i have no idea why) but if you have your own app, [follow the docs](https://github.com/jojo2357/Music-Discord-Rich-Presence#changing-default-background) to set that up.

if you have your own app, upload a `paused` asset, a `<player> small` and a `<player>` icon
