### ISSUE TITLE
Can't start the launcher

### ISSUE THREAD

**Issue by DerpWhite** [jojo2357/Music-Discord-Rich-Presence#82]
**Version**
1.7.2

**Describe the bug**
cmd show `FINDSTR: cannot open` with `Music_DRP_Launcher.bat` directory

**To Reproduce**
1. Go to `1.7.2_Release` folder
2. Click on `Music_DRP_Launcher.bat`
3. See error

**Screenshots**
<img width="674" alt="Screenshot 2023-04-05 111244" src="https://user-images.githubusercontent.com/56242831/229980030-b12d9430-02cc-4065-b3e8-49248eaa04b4.png">

**Comment by jojo2357** [comment]
I have no idea, so lets start with the easy questions:

Windows version?
Does OneDrive have anything to do with it?
- Try unzipping to a place, say downloads and running there?

If you go into `MDRP\bin\Release` can you still start `MDRP.exe`?

**Comment by DerpWhite** [comment]
Thank for replying, jojo2357

I turned off OneDrive for a long time before. Currently use Win10 Home 22H2 120.2212.4190.0.
I tried to unzip it in download folder and it work normally

**Comment by jojo2357** [comment]
Glad to hear of the success. I am always suspicious of OneDrive since it does a lot of things behind the scenes. 

Last question, for completeness, are there any special characters (special being **not** a letter, number, dash or underscore) or spaces in the censored path?

**Comment by DerpWhite** [comment]
The path contain some character from which it is only available on Unicode. It's the name of 'Document' default folder in my language.

**Comment by jojo2357** [comment]
Ah, I think that may be the cause of that issue. Thank you for reporting
