### ISSUE TITLE
Support for MediaMonkey5?

### ISSUE THREAD

**Issue by Vaarelsauce** [jojo2357/Music-Discord-Rich-Presence#84]
It would be nice if this program supports MediaMonkey5, as I couldn't find any other programs that could display MM5's music under Discord's Rich Presence status (aside from [one janky git source](https://github.com/MikeMcShaffry/kflipcamp/issues/14)).

**Comment by jojo2357** [comment]
Can you join my discord so i can send you a test program to see if MM5 is compatible?

**Comment by Vaarelsauce** [comment]
> Can you [join my discord](https://discord.gg/RUfykEZ4) so i can send you a test program to see if MM5 is compatible?

Sure, I'd be glad to!
