### ISSUE TITLE
Windows 10 Media Player doesn't render rich presence correctly.

### ISSUE THREAD

**Issue by illegitimate-egg** [jojo2357/Music-Discord-Rich-Presence#88]
## IF YOUR ISSUE...

Windows 10 Media Player metadata stops working after playing one track, it is also falsely detected as groove music.

**Version**
The version the bug was found on: 1.7.2

**Describe the bug**
When using the windows 10 media player, metadata is successfully loaded and displayed for the first track, though the application is displayed as groove music. Following the first track all metadata is just read as blank as shown in the screenshots below.

**To Reproduce**
1. Link Rich Presence with Media Player
2. Play more than one track

**Expected behavior**
The application displays the currently playing song in rich presence with the application appearing to be media player.

**Screenshots**
![image](https://github.com/jojo2357/Music-Discord-Rich-Presence/assets/63966843/d3fe128a-7a0c-49f5-9962-bccc1bb6b1b0)
![image](https://github.com/jojo2357/Music-Discord-Rich-Presence/assets/63966843/5b4f0992-eba8-4b61-9931-32a891f2716f)

**Comment by jojo2357** [comment]
This is a [well known issue](https://github.com/jojo2357/Music-Discord-Rich-Presence/issues/76) which has to do with WMP being bad software and not reporting its media to WMC (where mdrp reads the data from)
